### ISSUE TITLE
[EPIC] Cugraph Docs Migration Effort

### ISSUE THREAD

**Issue by nv-rliu** [rapidsai/cugraph-docs#57]
## Description

This issue should serve as the landing page for tracking all work relate to migrating the docs from `cugraph` -> `cugraph-docs`. Individual tasks will be defined below and any relevant discussion regarding the _state of _work_ should be done in this issue.

## Acceptance Criteria

These cover multiple issues in the Tasklist. Think of them as major milestones.

- [x] Docs are being published from the `cugraph-docs` repo and NOT `cugraph`
- [x] All docs code has been removed from the `cugraph` repo
- [x] Migrated pages match previous cugraph docs ( compare 24.12 with 25.02 )
- [x] cugraph C++ API is present

## Task List

- [x] #58
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #64

## Important Dates

Aim to get these goals done by Jan. 13, 2025 -- in-time for our monthly sync.

1) @nv-rliu to demo https://github.com/rapidsai/graph_dl/issues/614
2) @acostadon to show off the newly migrated cugraph docs
